server:
  port: 8080

spring:
  profiles:
    active: test
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017/driver_path?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
  # thread pool for async task
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8

management:
  health:
    defaults:
      enabled: false

logging:
  config: classpath:logback-test.xml

kafka:
  brockerList:
  topic:
  partitions:
  schemaRegistryUrl:
